---
# tasks file for deploy_apache_web
  - name: Check OS
    debug: 
      var: ansible_os_family
  
  - block: #Block for Ubuntu
    
    - name: Install Apache Web Server for Ubuntu
      apt: name=apache2 state=latest

    - name: Start Web Server and make it enable on boot for Ubuntu
      service: name=apache2 state=started enabled=yes
    
    - name: Copy MyWebSite to Ubuntu Servers
      copy: src=MyWebSite/ dest={{ destin_file }} mode=0555
      notify: Restart Apache Ubuntu

    when: ansible_os_family == "Debian"

  - block: #Block for RHEL

    - name: Install Apache Web Server for RHEL
      yum: name=httpd state=latest

    - name: Start Web Server and make it enable on boot for RHEL
      service: name=httpd state=started enabled=yes

    - name: Copy MyWebSite to RHEL  Servers
      copy: src=MyWebSite/ dest={{ destin_file }} mode=0555
      notify: Restart Apache RHEL
  
    when: ansible_os_family == "RedHat"

  - name: Generate index.html file
    template: src=index.j2 dest={{ destin_file }}/index.html mode=0555
    notify:
     - Restart Apache Ubuntu
     - Restart Apache RHEL
